import os

WEB_DIRECTORY = "./web"

from .minimax_h3_template_node import (
    NODE_CLASS_MAPPINGS as TEMPLATE_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as TEMPLATE_DISPLAY
)
from .minimax_h3_annotator_node import (
    NODE_CLASS_MAPPINGS as ANNOTATOR_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as ANNOTATOR_DISPLAY
)

NODE_CLASS_MAPPINGS = {**TEMPLATE_CLASS, **ANNOTATOR_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**TEMPLATE_DISPLAY, **ANNOTATOR_DISPLAY}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']